import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { useEffect } from "react";

const Home: NextPage = () => {
  useEffect(() => {});

  return (
    <div className={styles.container}>
      <Head>
        <title>Practice Redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>123</main>
    </div>
  );
};

export default Home;
