import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import styles from "../styles/Home.module.css";
import { useInputs } from "./components/useInputs";
import { useEffect } from "react";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Practice Redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>sfdg</main>
    </div>
  );
};

export default Home;
