import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getTheUsers } from "../store/actions";
import { AppState } from "../types/actions";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getTheUsers());
  }, []);
  const { data, page, per_page, total, total_pages } = useSelector<
    AppState,
    AppState["user"]
  >((state) => state.user);
  useEffect(() => {}, [data]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Practice Redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {data &&
            Object.entries(data).map(([i, item]) => {
              return (
                <li key={i}>
                  {" "}
                  <img src={item.avatar} alt={item.email} />
                  {item.id} {item.first_name} - {item.last_name}
                </li>
              );
            })}
        </ul>
      </main>
    </div>
  );
};

export default Home;
